### ISSUE TITLE
No token authentication

### ISSUE THREAD

**Issue by eudosia** [IntelligentVisibility/DropboxAPI#1]
I'm testing your code. I'm on Xojo 2015 r1. It doesn't work because in the string:
  Self.Dropbox_API_URL+"?grant_type=" + theGrantType + "&code="+_
  theAccessCode+"&client_id=" + theClientID + "&client_secret=" + theClientSecret + "&redirect_uri=https://www.google.com" 
'theAccessCode' variable is blank.

**Comment by eudosia** [comment]
I can notice the feedback url parameters is changed, so the parseCode function returns no code.
I have fixed It with:
  Parse_AccessCode_RegEx.SearchPattern = "(?<=\?gws_rd=cr&ei=).+"
  returning url --> https://www.google.com?gws_rd=cr&ei=T_MrVaOBG6KpyQPBtYDIBA
Now I have a code so in the API_Call_GetToken function there is a complete url....but....
the returning json from Dropbox got an error: the code doesn't exsists or has expired ..... ? Any idea ?
-->{"error_description": "code doesn't exist or has expired", "error": "invalid_grant"}
and the class doesn't manage the json errors

**Comment by mikecotrone** [comment]
Hi and I appreciate the feedback! Let me test the current Git version again to ensure all recent changes are reflected. Thanks!!

**Comment by eudosia** [comment]
I can report that https://www.google.com dont return a valid url.
I have tested with https://www.facebook.com and It returnet correct url 
with ?code= param
BR
Massimiliano

Il 13/04/15 19:27, Dev Group ha scritto:

> Hi and I appreciate the feedback! Let me test the current Git version 
> again to ensure all recent changes are reflected. Thanks!!
>

**Comment by mikecotrone** [comment]
Much appreciated Massimiliano. I will jump on this in a few hours. Thank you again!

**Comment by mikecotrone** [comment]
Ok so when I did this integration/testing it was on Xojo 2014 r3.2 and it still works as expected on 2014 3.2. I will check out R2015 r1 to see what the differences are.

**Comment by mikecotrone** [comment]
Ok it is working 100% per my Github code using Xojo 2015R1. Are you sure you are using your correct Dropbox API ID and Key? Are you sure you have the www.google.com (in my test code's case) on your redirected URI on your dropbox app?

**Comment by mikecotrone** [comment]
Since i can't find any issue with this report I will close this. Please let me know if you have any other issues with this project. Thank you.
